### ISSUE TITLE
Using different values of GODEBUG=cgocheck for dev and release builds

### ISSUE THREAD

**Issue by leogr** [falcosecurity/plugins#19]
**Motivation**

As per [cgo documentation](https://pkg.go.dev/cmd/cgo#hdr-Passing_pointers), complete checking of pointer handling can have some cost at run time. For this reason, it would be nice to set the value of `cgocheck` on a per-build basis.

**Feature**

Improve the building system in order to use:
- `GODEBUG=cgocheck=2` for development builds (a.k.a. debug release, usually published when a PR gets merged into `master`)
- `GODEBUG=cgocheck=0` for production builds (official distribution artifacts, published when tagging a release)

**Alternatives**

The do-nothing alternative? :smile_cat: 

**Additional context**

**Comment by leodido** [comment]
+1 from me
