### ISSUE TITLE
k8saudit extract additional fields

### ISSUE THREAD

**Issue by ronaldour** [falcosecurity/plugins#194]
**Motivation**

When using EKS the audit logs contain important information about the user under `user.extra` field which is not extracted by the plugin. 

The fields that are currently extracted by the plugin for the user are:

`user.name` --> `user.username`
`user.groups` --> `user.groups`

**Feature**

We would like to include those fields like `user.extra` to the extracted fields. Even better if we could make it dynamic or provide an easy way of extracting additional fields.

**Alternatives**

For now there are no alternatives to get that information on the event.

**Additional context**

Example of a full audit log from EKS:

```json
{
   "kind":"Event",
   "apiVersion":"audit.k8s.io/v1",
   "level":"RequestResponse",
   "auditID":"09dddf1c-01e4-4e0f-867d-eb430659575d",
   "stage":"ResponseComplete",
   "requestURI":"/api/v1/namespaces/default/pods/example-76dc5d5df9-s6b57/portforward",
   "verb":"create",
   "user":{
      "username":"admin",
      "uid":"aws-iam-authenticator:12345678910:ASLGADSLKASDFLKJHSAFLK",
      "groups":[
         "system:masters",
         "system:authenticated"
      ],
      "extra":{
         "accessKeyId":[
            "ASLGADSLKASDFLKJHSAFLK"
         ],
         "arn":[
            "arn:aws:iam::12345678910:role/admin/ronaldo.ur"
         ],
         "canonicalArn":[
            "arn:aws:iam::12345678910:role/admin"
         ],
         "sessionName":[
            "ronaldo.ur"
         ]
      }
   },
   "sourceIPs":[
      "1.2.3.4"
   ],
   "userAgent":"kubectl/v1.23.6 (linux/amd64) kubernetes/ad33385",
   "objectRef":{
      "resource":"pods",
      "namespace":"default",
      "name":"example-76dc5d5df9-s6b57",
      "apiVersion":"v1",
      "subresource":"portforward"
   },
   "responseStatus":{
      "metadata":{
         
      },
      "code":101
   },
   "requestReceivedTimestamp":"2022-12-16T23:18:20.112683Z",
   "stageTimestamp":"2022-12-16T23:18:21.859605Z",
   "annotations":{
      "authorization.k8s.io/decision":"allow",
      "authorization.k8s.io/reason":""
   }
}
```

We can create a PR to include those fields, but maybe we can discuss the possibility of making it dynamic?

**Comment by jasondellaluce** [comment]
I see no issues in adding new fields as the necessity comes. Be mindful that the "dynamic" part you're describing is already implemented by the `json` plugin. Such a plugin is compatible with any event source where the event payload is encoded as a json (such as k8s_audit and aws_cloudtrail). In your case you would be able to extract this info and use it as a rules with something like: `json.value[/user/extra/sessionName] contains ronaldo`

**Comment by sepulworld** [comment]
> I see no issues in adding new fields as the necessity comes. Be mindful that the "dynamic" part you're describing is already implemented by the `json` plugin. Such a plugin is compatible with any event source where the event payload is encoded as a json (such as k8s_audit and aws_cloudtrail). In your case you would be able to extract this info and use it as a rules with something like: `json.value[/user/extra/sessionName] contains ronaldo`


This seems to do the trick. Thanks @jasondellaluce for the recommendation!
```
            - rule: Port-forward to Pod
              desc: >
                Detect any attempt to porf-foward to a pod
              condition: ka.target.subresource in (portforward)
              output: Port-forward to pod (human=%json.value[/user/extra/sessionName] user=%ka.user.name pod=%ka.target.name resource=%ka.target.resource ns=%ka.target.namespace action=%ka.target.subresource command=%ka.uri.param[command])
              priority: NOTICE
              source: k8s_audit
              tags: [k8s]
```

**Comment by jasondellaluce** [comment]
You're welcome! Closing this as the issue seems to be solved, feel free to reopen it if you need further help.

/close
