### ISSUE TITLE
change plugins git tag convention to be go-compatible 

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/plugins#223]
**Motivation**

Currently, every plugin release is marked by a git tag with the naming convention `<plugin_name>-x.y.z`. This is also used by our CI to build and release plugin artifacts.

However, many/most plugins are developed in Go and the git tags for their release cannot be used to import the plugins' code in other Go projects because they don't respect the Go version convention for modules in subdirectories (see: https://go.dev/ref/mod#vcs-version).

**Feature**

Changing the naming convention from `<plugin_name>-x.y.z` to `plugins/<plugin_name>/vx.y.z`, which is compatible with the Go package manager and improves the code reusability of each plugin. We can easily adapt our CI to use this format for building release artifacts. Two birds with one stone.

**Alternatives**

**Additional context**

**Comment by leogr** [comment]
Question: May we want to release rules with a different version number too?

**Comment by jasondellaluce** [comment]
Good question. IMO, plugins and their rules should be released with two distinct tags and version numbers in the future. At that point, we can decide which naming convention we want to employ for the rules tags.

**Comment by leogr** [comment]
Quick update: As discussed with @jasondellaluce we intend to work on this immediately after Sept Falco's release.

cc @alacuku @LucaGuerra
