### ISSUE TITLE
Developer guide for plugins

### ISSUE THREAD

**Issue by RichardoC** [falcosecurity/plugins#225]
Is there a guide to getting started with building/testing the plugins, and how to add a new one?

An example from the [Kubernetes project ](https://github.com/kubernetes/community/tree/master/contributors/devel#readme)

Thanks!

**Comment by Issif** [comment]
Hi,
You can read our blog post which describes how to write a plugin. https://falco.org/blog/extend-falco-inputs-with-a-plugin-the-basics/

We'll trying to adapt it as a tutorial in the docs for future.

**Comment by RichardoC** [comment]
Thank you, I was attempting to follow that guide but ran in to issues where the libc on my machine doesn't match the version included in the falco container image I was running. Perhaps we could update this guide to use the same container image used to build the falco images to prevent this sort of issue?

My current (bad) approach has been to do the following (or building an image base don falco), to avoid this issue

```console

nerdctl run --rm -it -v$(pwd):/example:rw  --entrypoint="/bin/bash" falcosecurity/falco -c 'apt update ; apt --fix-broken install -y ; apt install -y wget && wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz && export PATH=$PATH:/usr/local/go/bin && cd /example && make clean && make && /usr/bin/falco -u  -c /example/examples/running-locally/falco.yaml  -r /example/examples/running-locally/falco_rules.yaml  --list-plugins'

```

Thanks!

**Comment by leogr** [comment]
cc @jasondellaluce

**Comment by leogr** [comment]
/remove-lifecycle stale

In the last months, our documentation has been revised and extended. I guess most of what the developers need is described at https://falco.org/docs/plugins/developers-guide/.


Do you think anything still needs to be added? :thinking:

**Comment by Issif** [comment]
I'm ok for closing this issue.

**Comment by RichardoC** [comment]
It's still missing build details like which glibc to target, which go versions to use and other toolchain like things
Instead of documenting it, it could be as simple as providing a container which can be used to generate compatible plugins?
My approach to this can be seen in the command in https://github.com/falcosecurity/plugins/issues/225#issuecomment-1412405353

**Comment by leogr** [comment]
> It's still missing build details like which glibc to target, which go versions to use and other toolchain like things

cc @LucaGuerra
