### ISSUE TITLE
k8s plugins should detect portforwards as well as execs

### ISSUE THREAD

**Issue by RichardoC** [falcosecurity/plugins#230]
**Motivation**

Currently the various example k8s alerting rules don't include detections for port-forwards.
Similar to the exec rule(s) there should be an example rule for port-forwards  because that actor could be sidestepping various network segmentation/auth steps.

**Feature**
Add port-forward detection, which should be almost identical to the exec detections

**Alternatives**

**Additional context**

**Comment by Andreagit97** [comment]
sorry right now we are quite full but for sure this is an interesting feature! would you be interested in implementing it?
