### ISSUE TITLE
ka.sourceips is always N/A

### ISSUE THREAD

**Issue by jasiam** [falcosecurity/plugins#236]
**Describe the bug**

ka.sourceips value is always `N/A` even the k8s audit event contains a valid ip.

**How to reproduce it**

Taking this k8s audit event:
```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Metadata",
  "auditID": "f6680d88-fa8e-4632-be24-4454439581a5",
  "stage": "ResponseComplete",
  "requestURI": "/apis/kyverno.io/v1alpha2/namespaces/ids/backgroundscanreports/a056be7f-bf34-4530-93a8-105c541585c4",
  "verb": "get",
  "user": {
    "username": "system:serviceaccount:core:kyverno",
    "uid": "055bd069-dbca-40d5-9dbd-26718003be43",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:core",
      "system:authenticated"
    ],
    "extra": {
      "authentication.kubernetes.io/pod-name": [
        "kyverno-76c7c75d75-wf949"
      ],
      "authentication.kubernetes.io/pod-uid": [
        "2c18b7cd-3053-4ba5-9f43-7936de39cb05"
      ]
    }
  },
  "sourceIPs": [
    "192.168.121.136"
  ],
  "userAgent": "kyverno/v0.0.0 (linux/amd64) kubernetes/$Format",
  "objectRef": {
    "resource": "backgroundscanreports",
    "namespace": "ids",
    "name": "a056be7f-bf34-4530-93a8-105c541585c4",
    "apiGroup": "kyverno.io",
    "apiVersion": "v1alpha2"
  },
  "responseStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "backgroundscanreports.kyverno.io \"a056be7f-bf34-4530-93a8-105c541585c4\" not found",
    "reason": "NotFound",
    "details": {
      "name": "a056be7f-bf34-4530-93a8-105c541585c4",
      "group": "kyverno.io",
      "kind": "backgroundscanreports"
    },
    "code": 404
  },
  "requestReceivedTimestamp": "2023-02-24T07:00:13.055259Z",
  "stageTimestamp": "2023-02-24T07:00:13.056314Z",
  "annotations": {
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"kyverno\" of ClusterRole \"kyverno\" to ServiceAccount \"kyverno/keos-core\""
  }
}
```
And having this rule in my custom rules file:

```
    - rule: Check unknown source IP
      desc: Detect an unknown ip address doing requests to Kube API Server
      condition: kevt
      output: Unknown ip request to Kube API Server (sourceips=%ka.sourceips useragent=%ka.useragent)
      priority: NOTICE
      source: k8s_audit
      tags: [k8s]
```
The falco event shows like this:

```
07:00:31.960363000: Notice Unknown ip request to Kube API Server (sourceips=<NA> useragent=kyverno/v0.0.0 (linux/amd64) kubernetes/$Format)
```

**Expected behaviour**

Falco event should contain the sourceIPs value from k8s audit event log

**Environment**

- Falco version:
0.34.1

- System info:
  **"machine": "x86_64",
    "nodename": "falco-7twq5",
    "release": "4.18.0-373.el8.x86_64",
    "sysname": "Linux",
    "version": "1 SMP Tue Mar 22 15:11:47 UTC 2022"**

- Cloud provider or hardware configuration:
  **Vagrant local k8s cluster (1.24)**

- OS:
  **CentOS Stream release 8**

- Kernel:
  **Linux m1 4.18.0-373.el8.x86_64** 

- Installation method:
**Chart**

- Additional comments:

I've also tried to debug the k8s_audit plugin with the extract_test.go but it seems the json is not decoded due the `if evtNum != e.jdataEvtnum`  condition (line 82 of extract.go) is never met. IDK if I can test it locally somehow.

All the others fields seems to be parsed correctly since I get the right value on the falco events from the rest of the rules.

**Comment by sanchaysaxena** [comment]
Hi @jasiam, i am facing the same issue, were you able to find a workaround or the reason why the value was coming as N/A.

**Comment by jasiam** [comment]
@sanchaysaxena I wasn't able to find any workaround, but to be honest I stopped using falco too at that time.
