### ISSUE TITLE
GCP audit events Plugin

### ISSUE THREAD

**Issue by SMR39** [falcosecurity/plugins#245]
**A new Plugin Request**

A plugin to read GCP audit events via pubsub topic.

I have noticed inside the slack community that there was some work regarding this. Is it still planned in roadmap?

**Comment by jasondellaluce** [comment]
Hi! I think the thread you're referring to is https://kubernetes.slack.com/archives/CMWH3EH32/p1665830293867959.
From my understanding, preliminary work was ongoing but there has not been any updates for quite a while. Is this something you'd be interested to work on?

**Comment by NissesSenap** [comment]
Seems like the plugin now have been made public https://github.com/ahmedameenaim/falco-plugin <3

**Comment by jasondellaluce** [comment]
The GCP plugin has been contributed to our org by @ahmedameenaim (thanks ❤️ ), and is now available at https://github.com/falcosecurity/plugins/tree/master/plugins/gcpaudit.

/close
