### ISSUE TITLE
[github] Add repo name as field

### ISSUE THREAD

**Issue by sboschman** [falcosecurity/plugins#300]
**Motivation**

Currently the `github.repo` field exposes the full repo url (`html_url` json field). To make processing the output with f.e. falcosidekick easier ([#falcosidekick 537](https://github.com/falcosecurity/falcosidekick/issues/537)) it would be great to have access to just the repo name as well.

**Feature**

Split the current `github.repo` field into `github.repo.name` and `github.repo.url` fields.  So `github.repo.name` provides the short repo name (`<repo>`) and `github.repo.url` provides the current value of `html_url` (`https://github.com/<owner>/<repo>`).

**Alternatives**

**Additional context**

**Comment by leogr** [comment]
This should be fixed by https://github.com/falcosecurity/plugins/pull/530
/close
