### ISSUE TITLE
GCP-Plugin Donation

### ISSUE THREAD

**Issue by ahmedameenaim** [falcosecurity/plugins#305]
**Motivation**

The GCP Audit Logs Plugin's primary purpose is to detect security threats, vulnerabilities, and compliance risks by analyzing the ingested GCP audit logs. The default security detection rules were built with the MITRE & ATT&CK framework in mind, which provides a comprehensive and industry-standard way to identify and classify different types of security threats.

The GCP Audit Logs Plugin can help security teams identify and respond to security incidents quickly, improve compliance posture, and reduce overall risk to the organization. It provides a comprehensive and centralized view of security events across multiple GCP services and can help detect and prevent unauthorized access, data exfiltration, and other types of malicious activity.

**Feature**

By leveraging GCP audit logs, the GCP Audit Logs Plugin provides deep insights into the activities of different users, services, and resources in your GCP environment. The GCP Audit Logs Plugin's advanced ebpf capabilities enable it to identify anomalous activities and raise alerts when it detects suspicious or malicious behavior.

The GCP Audit Logs Plugin also offers customizable detection rules that enable you to fine-tune the detection capabilities to suit your organization's specific needs. You can customize the rules to detect specific types of security threats, monitor specific users or services, and track specific resources or data types.

**Additional context**

The GCP Audit Logs Plugin comes with pre-built security detection rules designed to detect security threats based on the MITRE & ATT&CK framework. These rules are constantly updated to ensure that the security agent is always detecting the latest threats and vulnerabilities.

The default security detection rules cover the following areas:

Identity and Access Management (IAM)
Network Security
Data Security
Compliance
Infrastructure Security
Cloud Service Providers
The GCP Audit Logs Plugin's detection rules can identify threats such as:

Privilege escalation
Unauthorized access
Data exfiltration
Denial of Service (DoS) attacks
Insider threats
Suspicious network activity

**Comment by jasondellaluce** [comment]
I followed you so far, and it's a big +1 from me! Great project and super valuable contribution for our project! 🚀 

cc @falcosecurity/plugins-maintainers

**Comment by ahmedameenaim** [comment]
@jasondellaluce Thank you so much for your support!

**Comment by leogr** [comment]
Big +1 for me!

Thank you!
