### ISSUE TITLE
Add signatures to the generated index

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/plugins#306]
**Motivation**

When we release plugins we can now add signatures and check them (see example: https://github.com/falcosecurity/falcoctl/pull/305)
Now we need to make sure that the index file we generate contains the signature section accordingly

Note that for plugins, the index file could in the future also contain plugins that are not generated from this repository, so we may want to rely to those third-party trusted plugin authors to supply that signature and add it to this repo.

**Comment by maxgio92** [comment]
I can work on this
/assign
