### ISSUE TITLE
Release process cleanup: unify release, OCI publishing and signing workflows

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/plugins#350]
**Motivation**

The plugin release process has recently been improved with GHA. This is great because it can leverage GitHub release flow and publish directly to S3. The problem is that the OCI publishing step is still the older one which is overly complicated by the fact that the plugin building and releasing process used to be somewhere else, and so the OCI registry update step needed to do a lot of inference from git tags, the presence of S3 files and the existence of appropriate tags in the OCI registry. Many of those steps are now unnecessary and are prone to breakage.

**Feature**

Refactor the plugin release process/pipelines and add OCI updating and signing steps to the release pipeline for each artifact.

**Alternatives**

The current version is functional but results in wasted maintainer time at each release.

**Comment by alacuku** [comment]
Done in #440
