### ISSUE TITLE
falco load k8s audit rules failed

### ISSUE THREAD

**Issue by woniuzhang** [falcosecurity/plugins#550]
/etc/falco/k8s_audit_rules.yaml | schema validation: failed for <root>[11]: Value type not permitted by 'type' constraint.

Using helm chart install falco and use values-k8saudit.yaml as value file

Chart.yaml
apiVersion: v2
appVersion: 0.39.1
dependencies:
- condition: falcosidekick.enabled
  name: falcosidekick
  repository: https://falcosecurity.github.io/charts
  version: 0.8.*
- condition: collectors.kubernetes.enabled
  name: k8s-metacollector
  repository: https://falcosecurity.github.io/charts
  version: 0.1.*
description: Falco
home: https://falco.org
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: cncf-falco-dev@lists.cncf.io
  name: The Falco Authors
name: falco
sources:
- https://github.com/falcosecurity/falco
version: 4.11.1

**Comment by leogr** [comment]
Hey @woniuzhang 

The problem has been fixed already, you should use the latest plugins and rules version, which is 0.11.

I've also prepared https://github.com/falcosecurity/charts/pull/799 for our helm charts to bump k8saudit to the latest version.

Please let me know if that solves your issue. Thank you :pray:
