### ISSUE TITLE
Consider make falco-plugin-scoffolding repository

### ISSUE THREAD

**Issue by Dentrax** [falcosecurity/plugins#63]
**Motivation**

The idea is inspired by [terraform-provider-scaffolding](https://github.com/hashicorp/terraform-provider-scaffolding) project, which makes life easier to create custom providers from scratch by using [template-project](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository). In this project, we have [plugins](https://github.com/falcosecurity/plugins) folder to demonstrate how can we create custom plugins from scratch.

We (w/@developer-guy @erkanzileli) are proposing to create brand-new batteries-included public template repository for the developer who do not want to do chore things.

**Feature**

Since _plugins_ mostly written in Go, I'll go with Go here:

To provide batteries-included project:

* `.gitignore`
* `.goreleaser.yml`
* `.golangci-lint.yml`
* `docs/`
* `.github/`
*  * dependabot
*  * ISSUE + PR Templates
* * workflows: `test` + `build`
* CONTRIBUTING.md
* OWNERS
* LICENSE
* [just](https://github.com/casey/just) or [make](https://man7.org/linux/man-pages/man1/make.1.html) file
* * build: go build (ldflags for version)
* * test: unit + integrations
* * fmt: format checking
* * lint: linters

**Alternatives**

If we don't want to complicate simple things, `plugins` folder is just fine to get started. This is just for an idea.

**Additional context**

`-`

**Comment by leogr** [comment]
Hey @Dentrax 

this is a fantastic idea! :star_struck: 

I also want to add more context regarding using the [plugins](https://github.com/falcosecurity/plugins/tree/master/plugins) folder in this repo VS. creating a new repository.

We support both cases. 

Our idea is that plugins owned by the Falcosecurity org should be [hosted](https://github.com/falcosecurity/plugins#hosted-plugins) inside the `/plugins` folder. In this way, we can have more control and publish official plugins at https://download.falco.org/?prefix=plugins/stable/. So we don't expect to create new repositories for plugins under the Falcosecurity org. For this case, we could add a `/templates` folder and then add `/templates/go` with just the essential files (like the `Makefile`). Note that the automation is already implemented in this repository using our bot.

On the other hand, we still support plugins that live elsewhere and are not owned by Falcosecurity. In such a case having a plugin-template repository would be great for all folks that want to host their plugin in their repositories. If you want to create the template repository, you can start creating one under your GitHub account and when ready you can transfer it to the falcosecurity organization. Let me know, I will help you with all the formalities.

:+1:

**Comment by leogr** [comment]
Any updates on this?
